import {
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  OnInit,
  ViewChild,
} from '@angular/core';

@Component({
  selector: 'app-main',
  templateUrl: './main.component.html',
  styleUrls: ['./main.component.scss'],
})
export class MainComponent {
  @ViewChild('content') content!: ElementRef<HTMLDivElement>;
  @Input() sidebarCollapsed: boolean = false;
  filtersCollapsed: boolean = false;
  categories: any[] = [
    {
      active: false,
      name: 'Onlayn kart sifarişi',
      processes: [
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
      ],
    },
    {
      active: false,
      name: 'Kredit sifarişi',
      processes: [
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
      ],
    },
    {
      active: false,
      name: 'HÖP üzrə daxili portal',
      processes: [
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
      ],
    },
    {
      active: false,
      name: 'VisaB2B',
      processes: [
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
      ],
    },
    {
      active: false,
      name: 'XÖHKS portal',
      processes: [
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
      ],
    },
    {
      active: false,
      name: 'Karta mədaxil',
      processes: [
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
      ],
    },
    {
      active: false,
      name: 'Elektron kassa',
      processes: [
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
        {
          id: '1247D980-35BF-CAB3-7679-CCE584BC11EB',
          channel: 'WS',
          customer: 'Əhmədov Saleh Nazim - 5H3VE46',
          branch: '(010)',
          card_duration: 'Müddəti - 2il',
          card_type: 'Mastercard Gold',
          currency: 'USD',
          status: 'Əməliyyatçıya yönləndirildi',
        },
      ],
    },
  ];

  scrollToElement(element: ElementRef) {
    setTimeout(() => {
      console.log(element.nativeElement.parentElement.offsetLeft);

      this.content.nativeElement.scrollTo(
        element.nativeElement.parentElement.offsetLeft - 25,
        0
      );
    }, 450);
  }
  toggleFilters() {
    this.filtersCollapsed = !this.filtersCollapsed;
    if (!this.filtersCollapsed) {
    }
  }
}
